/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';

import { AjonpFirebaseApp as AjonpFirebaseApp } from './components/ajonp-firebase-app/ajonp-firebase-app';

interface HTMLAjonpFirebaseAppElement extends AjonpFirebaseApp, HTMLElement {
}
declare var HTMLAjonpFirebaseAppElement: {
  prototype: HTMLAjonpFirebaseAppElement;
  new (): HTMLAjonpFirebaseAppElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "ajonp-firebase-app": HTMLAjonpFirebaseAppElement;
  }
  interface ElementTagNameMap {
      "ajonp-firebase-app": HTMLAjonpFirebaseAppElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "ajonp-firebase-app": JSXElements.AjonpFirebaseAppAttributes;
      }
  }
  namespace JSXElements {
      export interface AjonpFirebaseAppAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          apiKey?: string,
          authDomain?: string,
          databaseURL?: string,
          projectId?: string,
          storageBucket?: string,
          messagingSenderId?: string
      }
  }
}

import { AjonpFirebaseAuthDemo as AjonpFirebaseAuthDemo } from './components/ajonp-firebase-auth-demo/ajonp-firebase-auth-demo';

interface HTMLAjonpFirebaseAuthDemoElement extends AjonpFirebaseAuthDemo, HTMLElement {
}
declare var HTMLAjonpFirebaseAuthDemoElement: {
  prototype: HTMLAjonpFirebaseAuthDemoElement;
  new (): HTMLAjonpFirebaseAuthDemoElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "ajonp-firebase-auth-demo": HTMLAjonpFirebaseAuthDemoElement;
  }
  interface ElementTagNameMap {
      "ajonp-firebase-auth-demo": HTMLAjonpFirebaseAuthDemoElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "ajonp-firebase-auth-demo": JSXElements.AjonpFirebaseAuthDemoAttributes;
      }
  }
  namespace JSXElements {
      export interface AjonpFirebaseAuthDemoAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
      }
  }
}

import { AjonpFirebaseAuth as AjonpFirebaseAuth } from './components/ajonp-firebase-auth/ajonp-firebase-auth';

interface HTMLAjonpFirebaseAuthElement extends AjonpFirebaseAuth, HTMLElement {
}
declare var HTMLAjonpFirebaseAuthElement: {
  prototype: HTMLAjonpFirebaseAuthElement;
  new (): HTMLAjonpFirebaseAuthElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "ajonp-firebase-auth": HTMLAjonpFirebaseAuthElement;
  }
  interface ElementTagNameMap {
      "ajonp-firebase-auth": HTMLAjonpFirebaseAuthElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "ajonp-firebase-auth": JSXElements.AjonpFirebaseAuthAttributes;
      }
  }
  namespace JSXElements {
      export interface AjonpFirebaseAuthAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          signInWithRedirect?: any,
          id?: string,
          user?: string,
          provider?: string
      }
  }
}

