/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';

import { drinkpublic as AjonpDrinkpublic } from './components/ajonp-drinkpublic/ajonp-drinkpublic';

interface HTMLAjonpDrinkpublicElement extends AjonpDrinkpublic, HTMLElement {
}
declare var HTMLAjonpDrinkpublicElement: {
  prototype: HTMLAjonpDrinkpublicElement;
  new (): HTMLAjonpDrinkpublicElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "ajonp-drinkpublic": HTMLAjonpDrinkpublicElement;
  }
  interface ElementTagNameMap {
      "ajonp-drinkpublic": HTMLAjonpDrinkpublicElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "ajonp-drinkpublic": JSXElements.AjonpDrinkpublicAttributes;
      }
  }
  namespace JSXElements {
      export interface AjonpDrinkpublicAttributes extends HTMLAttributes {
        
      }
  }
}

